on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Format
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install mvdan.cc/gofumpt@latest
        goimports -w .
        gofumpt -w .
        d="$(git diff)"; [ -n "$d" ] && echo $d && exit 1

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet -v ./...
